Remove dependency on mysqlclient
HLFH/automua pull request #13
Opened 2022-12-25 16:44 UTC by mss

mysqlclient is just one possible backend for SQLAlchemy and requires various native build stuff to be installed. Since it is possible to use automua with PyMySQL or completely different databases as well it shouldn't be a hard dependency.

2022-12-29 21:19 UTC, HLFH commented
Hi,

Thanks!
I'll look into it on 30/12.

2023-01-03 16:54 UTC, HLFH requested changes
Only the change in `pyproject.toml` could be approved and without the trailing comma.
And the *.txt files need to be updated with `pip-tools`, not manually.

2023-01-03 16:54 UTC, HLFH commented on pyproject.toml
>      'lxml==4.9.1',
I'd remove the trailing comma

2023-01-03 16:54 UTC, HLFH commented on pyproject.toml
> +]
Not sure what has been done here.

2023-01-03 16:54 UTC, HLFH commented on requirements-ci.txt
> +# by the following command:
Why renaming the default content of the autogenerated files of [`pip-tools`](https://github.com/jazzband/pip-tools)?

2023-01-03 16:54 UTC, HLFH commented on requirements-test.txt
> +# by the following command:
Why renaming the default content of the autogenerated files of [`pip-tools`](https://github.com/jazzband/pip-tools)?

2023-01-03 16:54 UTC, HLFH commented on requirements.txt
> +# by the following command:
Why renaming the default content of the autogenerated files of [`pip-tools`](https://github.com/jazzband/pip-tools)?

2023-01-03 17:20 UTC, HLFH commented
The 2022.8.2 release has been [submitted on Pypi](https://pypi.org/project/automua/) and [on Arch Linux](https://aur.archlinux.org/packages/automua). It has removed `mysqlclient` as a dependency. I have also updated automatically the *.txt files with `pip-compile` and updated the resolver to `backtracking`.

2023-01-03 17:20 UTC, closed without merging

2023-01-04 09:24 UTC, HLFH commented
`mysqlclient` has been added as optdepend. https://github.com/HLFH/automua/commit/d80527d81cc2aabddca99868e899fe4afb2f69fc

2023-01-04 17:06 UTC, mss commented on pyproject.toml
> +]
I think my editor added a newline at the end of the file.

2023-01-04 17:08 UTC, mss commented
@HLFH thanks for applying this!

Regarding your comments to the `requirements.txt` files: I actually used `pip-compile` to generate them. I guess I used a different version than yours which changed those comments.